version: "3"
services:
  bookstore:
    image: lyotam/ndb-bookstore:latest
    ports:
      - "8080:8080"
    networks:
      - bookstore-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    ports:
      - "33066:3306"
    restart: always
    networks:
      - bookstore-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toorpass
      - MYSQL_DATABASE=ndb_bookstore

networks:
  bookstore-mysql: